"use client";
import { useCallback, useEffect, useState } from "react";
import { displayLabel } from "./labels";
interface Worker { workerID: number; firstName: string; lastName: string; isActive: boolean; }
interface Allocation { workPlanItemID: number; workDate: string; taskID: number | null; workerID: number | null; workerName: string | null; area: string | null; taskDescription: string; priority: string; plannedStart: string | null; plannedEnd: string | null; materialsRequired: string | null; managerNote: string | null; status: string; calendarSyncStatus: string | null; calendarSyncError: string | null; calendarEventID: string | null; }
const api = process.env.NEXT_PUBLIC_API_URL;
const field = "mt-1 w-full rounded-xl border border-white/15 bg-zinc-900 p-3 text-white";
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Africa/Johannesburg", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
export default function LogisticsAllocationBoard({ workers }: { workers: Worker[] }) {
    const [date, setDate] = useState(today);
    const [items, setItems] = useState<Allocation[]>([]);
    const [edit, setEdit] = useState<Allocation | null>(null);
    const [error, setError] = useState("");
    const [busy, setBusy] = useState(false);
    const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token")}` });
    const load = useCallback(async () => {
        try { const response = await fetch(`${api}/api/LogisticsWorkPlan?date=${date}`, { headers: headers() }); if (!response.ok) throw new Error("Werkplan kon nie gelaai word nie."); setItems(await response.json()); }
        catch (e) { setError(e instanceof Error ? e.message : "Werkplan kon nie gelaai word nie."); }
    }, [date]);
    useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
    async function mutate(path: string, method: string, body?: unknown) {
        setBusy(true); setError("");
        try {
            const response = await fetch(`${api}/api/LogisticsWorkPlan${path}`, { method, headers: headers(), ...(body ? { body: JSON.stringify(body) } : {}) });
            if (!response.ok) { const result = await response.json(); throw new Error(result.message || "Werkplan kon nie gestoor word nie."); }
            if (path.endsWith("/calendar-sync")) { const result = await response.json(); if (!result.synced) setError("Kalendersinkronisering is afgeskakel of het misluk. Sien die itemstatus."); }
            setEdit(null); await load();
        } catch (e) { setError(e instanceof Error ? e.message : "Aksie het misluk."); } finally { setBusy(false); }
    }
    const groups = Array.from(new Set(items.map(item => item.workerID ?? 0))).sort((a,b) => a-b);
    return <section id="werkplan" className="nkrn-panel mb-8 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-semibold">Werkplan per werker</h2><p className="mt-2 text-sm text-zinc-300">Ken werk toe, herbeplan datums en volg kalenderstatus.</p></div><div className="flex flex-wrap gap-2"><input aria-label="Werkplandatum" type="date" className={field} value={date} onChange={e => setDate(e.target.value)} /><button className="q4-nav" onClick={() => setDate(today())}>Vandag</button><button className="q4-nav" onClick={() => void load()}>Verfris</button><button className="q4-nav" onClick={() => setEdit({workPlanItemID:0,workDate:date,taskID:null,workerID:null,workerName:null,area:"",taskDescription:"",priority:"P3",plannedStart:null,plannedEnd:null,materialsRequired:"",managerNote:"",status:"Beplan",calendarSyncStatus:null,calendarSyncError:null,calendarEventID:null})}>+ Beplan werk</button></div></div>
        {error && <p role="alert" className="my-3 text-red-300">{error}</p>}
        <div className="mt-6 grid gap-5 lg:grid-cols-2">{groups.map(id => <article key={id} className="rounded-2xl border border-white/15 p-4"><h3 className="text-lg font-semibold text-[#e7b42b]">{items.find(item => (item.workerID ?? 0) === id)?.workerName || "Nie toegeken nie"}</h3>{items.filter(item => (item.workerID ?? 0) === id).map(item => <div key={item.workPlanItemID} className="mt-4 border-t border-white/10 pt-4"><p className="font-semibold">{item.taskDescription}</p><p className="text-sm text-zinc-300">{item.priority} · {item.area} · {displayLabel(item.status)}</p><p className="text-sm">{item.plannedStart?.slice(0,5)} {item.plannedEnd && `– ${item.plannedEnd.slice(0,5)}`}</p><p className="text-sm">Materiaal: {item.materialsRequired || "—"}</p><p className="text-sm">Nota: {item.managerNote || "—"}</p><p className="mt-2 text-xs text-zinc-300">Kalender: {displayLabel(item.calendarSyncStatus) || "Nog nie gekoppel"}</p>{item.calendarSyncError && <p className="text-xs text-red-300">{item.calendarSyncError}</p>}<div className="mt-3 flex flex-wrap gap-2"><button className="q4-nav" disabled={busy || item.status === "Cancelled"} onClick={() => setEdit({...item,workDate:item.workDate.slice(0,10)})}>Wysig / Hertoeken</button><button className="q4-nav" disabled={busy || ["Cancelled","Afgehandel"].includes(item.status)} onClick={() => void mutate(`/${item.workPlanItemID}/complete`,"POST")}>Afgehandel</button><button className="q4-nav" disabled={busy} onClick={() => void mutate(`/${item.workPlanItemID}/calendar-sync`,"POST")}>Sinkroniseer kalender</button>{item.status !== "Cancelled" && <button className="q4-nav" disabled={busy} onClick={() => { if (window.confirm("Kanselleer hierdie werktoewysing?")) void mutate(`/${item.workPlanItemID}`,"PUT",{...item,status:"Cancelled"}); }}>Kanselleer</button>}</div></div>)}</article>)}</div>
        {items.length === 0 && <p className="mt-5 text-zinc-300">Geen werk vir hierdie datum nie.</p>}
        {edit && <form className="mt-6 rounded-2xl border border-[#d7a31f]/40 p-5" onSubmit={e => {e.preventDefault(); void mutate(edit.workPlanItemID ? `/${edit.workPlanItemID}` : "",edit.workPlanItemID ? "PUT" : "POST",{...edit,plannedStart:edit.plannedStart ? `${edit.plannedStart.slice(0,5)}:00` : null,plannedEnd:edit.plannedEnd ? `${edit.plannedEnd.slice(0,5)}:00` : null});}}><h3 className="text-xl font-semibold">Beplan en ken toe</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Werker<select className={field} value={edit.workerID ?? ""} onChange={e => setEdit({...edit,workerID:e.target.value ? Number(e.target.value):null})}><option value="">Nie toegeken nie</option>{workers.filter(w => w.isActive || w.workerID === edit.workerID).map(w => <option key={w.workerID} value={w.workerID}>{w.firstName} {w.lastName}</option>)}</select></label><label>Werkdatum<input required type="date" className={field} value={edit.workDate.slice(0,10)} onChange={e => setEdit({...edit,workDate:e.target.value})} /></label><label>Beskrywing<input required className={field} value={edit.taskDescription} onChange={e => setEdit({...edit,taskDescription:e.target.value})} /></label><label>Gebied<input className={field} value={edit.area ?? ""} onChange={e => setEdit({...edit,area:e.target.value})} /></label><label>Prioriteit<select className={field} value={edit.priority} onChange={e => setEdit({...edit,priority:e.target.value})}>{["P1","P2","P3","P4"].map(p => <option key={p}>{p}</option>)}</select></label><label>Status<select className={field} value={edit.status} onChange={e => setEdit({...edit,status:e.target.value})}>{Array.from(new Set([edit.status,"Beplan","In Proses","Staan oor","Afgehandel","Cancelled"])).map(s => <option key={s} value={s}>{displayLabel(s)}</option>)}</select></label><label>Begintyd<input type="time" className={field} value={edit.plannedStart?.slice(0,5) ?? ""} onChange={e => setEdit({...edit,plannedStart:e.target.value})} /></label><label>Eindtyd<input type="time" className={field} value={edit.plannedEnd?.slice(0,5) ?? ""} onChange={e => setEdit({...edit,plannedEnd:e.target.value})} /></label><label>Materiaal<textarea className={field} value={edit.materialsRequired ?? ""} onChange={e => setEdit({...edit,materialsRequired:e.target.value})} /></label><label>Bestuurdersnota<textarea className={field} value={edit.managerNote ?? ""} onChange={e => setEdit({...edit,managerNote:e.target.value})} /></label></div><div className="mt-4 flex gap-3"><button disabled={busy} className="q4-nav" type="submit">Stoor toewysing</button><button type="button" className="q4-nav" onClick={() => setEdit(null)}>Sluit</button></div></form>}
    </section>;
}
