// Display-only translation. Never use these labels as API or database values.
const labels: Record<string, string> = {
    "Request for": "Versoek vir",
    "Requester": "Versoeker",
    "Logged by": "Aangemeld deur",
    "Myself": "Myself",
    "Loading requesters...": "Gebruikers laai...",
    "Request submitted for": "Versoek ingedien vir",
    "Please select an active requester.": "Kies asseblief 'n aktiewe gebruiker.",
    "Only admins may log requests for another person.": "Slegs administrateurs mag versoeke namens iemand anders indien.",
    "Check the request details and select an active requester with a valid email address.": "Gaan die versoekbesonderhede na en kies 'n aktiewe gebruiker met 'n geldige e-posadres.",
    "Unable to load requesters. Refresh the page to try again.": "Gebruikers kon nie gelaai word nie. Verfris die bladsy om weer te probeer.",
    "The selected person will receive request emails and see the request in their history. You remain recorded as the person who logged it.": "Die gekose persoon ontvang die versoek se e-posse en sien dit in hul geskiedenis. Jy bly aangeteken as die persoon wat dit aangemeld het.",
    "Logged": "Aangemeld",
    "Busy": "Besig",
    "Done": "Afgehandel",
    "Low": "Laag",
    "Medium": "Medium",
    "High": "Hoog",
    "Critical": "Kritiek",
    "Requests": "Versoeke",
    "Assigned Technician": "Toegewysde tegnikus",
    "Comments": "Kommentaar",
    "Admin": "Administrasie",
    "Category": "Kategorie",
    "Describe the problem": "Beskryf die probleem",
    "Helpdesk": "IT-ondersteuning",
    "History": "Geskiedenis",
    "IT Request": "IT-versoek",
    "Loading categories...": "Kategorieë laai…",
    "Loading your account...": "Jou rekening laai…",
    "Log Out": "Meld af",
    "Logout": "Meld af",
    "My Requests": "My versoeke",
    "NKRN Home": "Tuis",
    "No categories available": "Geen kategorieë beskikbaar nie",
    "No requests logged yet.": "Nog geen versoeke aangemeld nie.",
    "Pending IT Desk": "Wag op IT-ondersteuning",
    "Please describe what is happening. You may also include a suggested due date or other important information here.": "Beskryf wat gebeur. Jy kan ook ’n voorgestelde sperdatum of ander belangrike inligting hier byvoeg.",
    "Please select a category before submitting the request.": "Kies ’n kategorie voordat jy die versoek indien.",
    "Priority": "Prioriteit",
    "Request submitted successfully.": "Jou versoek is ingedien.",
    "Request title": "Versoektitel",
    "Something went wrong submitting your request.": "Jou versoek kon nie ingedien word nie. Probeer asseblief weer.",
    "Submit Request": "Dien versoek in",
    "Submit a Request": "Dien ’n versoek in",
    "Submitting...": "Besig om in te dien…",
    "Tech Dashboard": "Tegnikusportaal",
    "Tell the IT team what you need assistance with.": "Vertel die IT-span waarmee jy hulp benodig.",
    "Unable to load request categories.": "Die versoekkategorieë kon nie gelaai word nie.",
    "Unable to load your requests.": "Jou versoeke kon nie gelaai word nie.",
    "Unknown": "Onbekend",
    "View the status of requests you have submitted.": "Volg die status van jou ingediende versoeke.",
    "You can include a preferred completion date, deadline, or other important information in the description.": "Jy kan ’n voorkeurdatum, sperdatum of ander belangrike inligting by die beskrywing insluit.",
    "e.g. Projector not displaying": "bv. Die projektor wys geen beeld nie",
    "(Admin)": "(Administrateur)",
    "Add Comment": "Voeg kommentaar by",
    "Add an internal comment...": "Voeg interne kommentaar by…",
    "All": "Alles",
    "All helpdesk requests": "Alle IT-ondersteuningsversoeke",
    "All priorities": "Alle prioriteite",
    "All statuses": "Alle statusse",
    "Assign to": "Ken toe aan",
    "Assigned To": "Toegewys aan",
    "Assigned to": "Toegewys aan",
    "Awaiting attention": "Wag op aandag",
    "Close": "Sluit",
    "Completed": "Afgehandel",
    "Completed Date": "Afhandelingsdatum",
    "Created": "Aangemeld op",
    "Created Date": "Aanmelddatum",
    "Currently Assigned To": "Tans toegewys aan",
    "Currently being handled": "Word tans hanteer",
    "Description": "Beskrywing",
    "Export CSV": "Voer CSV uit",
    "IT Technician Dashboard": "IT-tegnikusportaal",
    "In Progress": "Besig",
    "Internal Comments": "Interne kommentaar",
    "Loading comments...": "Kommentaar laai…",
    "Loading technician dashboard...": "Tegnikusportaal laai…",
    "Manage Request": "Bestuur versoek",
    "Mark Done": "Merk as afgehandel",
    "No comments yet.": "Nog geen kommentaar nie.",
    "No requests match the current filters.": "Geen versoeke pas by die gekose filters nie.",
    "Quick Actions": "Vinnige aksies",
    "Refresh": "Verfris",
    "Request": "Versoek",
    "Request ID": "Versoeknommer",
    "Resolved requests": "Afgehandelde versoeke",
    "Save Changes": "Stoor veranderinge",
    "Saving...": "Besig om te stoor…",
    "Search requests...": "Soek versoeke…",
    "Filter requests by status": "Filtreer versoeke volgens status",
    "Showing": "Wys",
    "of": "van",
    "matching requests": "ooreenstemmende versoeke",
    "Show fewer": "Wys minder",
    "Show all matching requests": "Wys alle ooreenstemmende versoeke",
    "Select a request to view, assign and update it.": "Kies ’n versoek om dit te bekyk, toe te wys of op te dateer.",
    "Something went wrong while updating the request.": "Die versoek kon nie opgedateer word nie. Probeer asseblief weer.",
    "Status": "Status",
    "Support Requests": "Ondersteuningsversoeke",
    "Technician": "Tegnikus",
    "Title": "Titel",
    "Total Requests": "Totale versoeke",
    "Unable to add the comment.": "Die kommentaar kon nie bygevoeg word nie.",
    "Unable to load the technician dashboard.": "Die tegnikusportaal kon nie gelaai word nie.",
    "Unassigned": "Nie toegeken nie",
    "Unknown technician": "Onbekende tegnikus",
    "+ Add User": "+ Voeg gebruiker by",
    "A user with this email address already exists.": "Daar is reeds ’n gebruiker met hierdie e-posadres.",
    "Actions": "Aksies",
    "Add NKRN User": "Voeg NKRN-gebruiker by",
    "Add progress comment": "Voeg ’n vorderingsnota by",
    "Adding...": "Besig om by te voeg…",
    "Administration": "Administrasie",
    "Administrator": "Administrateur",
    "Administrators": "Administrateurs",
    "All IT requests were exported successfully.": "Alle IT-versoeke is uitgevoer.",
    "Calendar appointments": "Kalenderafsprake",
    "Calendar event linked": "Kalenderafspraak gekoppel",
    "Cancel": "Kanselleer",
    "Cancel Add User": "Kanselleer nuwe gebruiker",
    "Comments & Progress": "Kommentaar en vordering",
    "Communication": "Kommunikasie",
    "Completed requests": "Afgehandelde versoeke",
    "Create User": "Skep gebruiker",
    "Creating User...": "Gebruiker word geskep…",
    "Edit": "Wysig",
    "Email": "E-pos",
    "Email address": "E-posadres",
    "Enter a progress update...": "Voeg ’n vorderingsnota by…",
    "Failed to add comment.": "Die kommentaar kon nie bygevoeg word nie.",
    "Failed to add user.": "Die gebruiker kon nie bygevoeg word nie.",
    "Failed to load requests.": "Die versoeke kon nie gelaai word nie.",
    "Failed to remove user.": "Die gebruiker kon nie gedeaktiveer word nie.",
    "Failed to update request.": "Die versoek kon nie opgedateer word nie.",
    "Failed to update user.": "Die gebruiker kon nie opgedateer word nie.",
    "First Name": "Voornaam",
    "First name": "Voornaam",
    "First name, last name and email address are required.": "Voornaam, van en e-posadres is verpligtend.",
    "Google Calendar Event ID": "Google Calendar-afspraaknommer",
    "Google Calendar event connected": "Google Calendar-afspraak gekoppel",
    "Hide Done Requests": "Versteek afgehandelde versoeke",
    "Hide Users": "Versteek gebruikers",
    "High-priority requests": "Hoëprioriteitsversoeke",
    "IT Desk Control Centre": "IT-beheersentrum",
    "IT Requests": "IT-versoeke",
    "Invalid date": "Ongeldige datum",
    "Invalid user role.": "Ongeldige gebruikersrol.",
    "Laerskool Tygerpoort · IT Desk · Administrator": "Laerskool Tygerpoort · IT-verslag · Administrateur",
    "Laerskool Tygerpoort · IT Desk": "Laerskool Tygerpoort · IT-verslag",
    "Laerskool Tygerpoort Logo": "Laerskool Tygerpoort-logo",
    "Last Name": "Van",
    "Last name": "Van",
    "Loading Administrator Dashboard...": "Administrasieportaal laai…",
    "Name": "Naam",
    "No active requests.": "Geen aktiewe versoeke nie.",
    "No appointment scheduled": "Geen afspraak beplan nie",
    "No comments have been added to this request yet.": "Daar is nog geen kommentaar op hierdie versoek nie.",
    "Not scheduled": "Nog nie beplan nie",
    "Only @tygies.co.za email addresses are allowed.": "Slegs @tygies.co.za-e-posadresse word toegelaat.",
    "Please enter a comment before adding it.": "Tik eers jou kommentaar in.",
    "Remove": "Deaktiveer",
    "Removing...": "Besig om te deaktiveer…",
    "Role": "Rol",
    "Save": "Stoor",
    "Scheduled": "Beplan",
    "Scheduled End": "Beplande eindtyd",
    "Scheduled Start": "Beplande begintyd",
    "Scheduled end": "Beplande eindtyd",
    "Scheduled start": "Beplande begintyd",
    "Show Done Requests": "Wys afgehandelde versoeke",
    "Show Users": "Wys gebruikers",
    "Submitted by": "Ingedien deur",
    "System Overview": "Stelseloorsig",
    "Technicians": "Tegnici",
    "The scheduled end time must be after the scheduled start time.": "Die beplande eindtyd moet ná die begintyd wees.",
    "There are no requests to export.": "Daar is geen versoeke om uit te voer nie.",
    "Unable to add user.": "Die gebruiker kon nie bygevoeg word nie.",
    "Unable to load the IT Desk data.": "Die IT-inligting kon nie gelaai word nie.",
    "Unable to remove user.": "Die gebruiker kon nie gedeaktiveer word nie.",
    "Unable to update user.": "Die gebruiker kon nie opgedateer word nie.",
    "Uncategorised": "Geen kategorie",
    "User": "Personeellid",
    "User Administration": "Gebruikersadministrasie",
    "User Email": "Gebruiker se e-posadres",
    "User ID": "Gebruikersnommer",
    "User Name": "Gebruiker se naam",
    "You are not authorised to add users.": "Jy het nie toestemming om gebruikers by te voeg nie.",
    "You are not authorised to manage users.": "Jy het nie toestemming om gebruikers te bestuur nie.",
    "You are not authorised to remove users.": "Jy het nie toestemming om gebruikers te deaktiveer nie.",
    "You are not authorised to update this request.": "Jy het nie toestemming om hierdie versoek op te dateer nie.",
    "You cannot remove your own account.": "Jy kan nie jou eie rekening deaktiveer nie.",
    "Logged in as": "Aangemeld as",
    "Comment added successfully.": "Kommentaar is bygevoeg.",
    "Failed to fetch": "Die verbinding het misluk. Probeer asseblief weer.",
    "NetworkError when attempting to fetch resource.": "Die verbinding het misluk. Probeer asseblief weer.",
    "Hardware": "Hardeware",
    "Software": "Sagteware",
    "Network": "Netwerk",
    "Internet": "Internet",
    "Printer": "Drukker",
    "Printing": "Drukwerk",
    "Other": "Ander"
};

// Shared by the language shell so the complete IT/Admin/Tech vocabulary can
// be switched in both directions without changing API or database values.
export const itTranslations = Object.entries(labels).map(([en, af]) => ({
    en,
    af,
}));

export function itLabel(value: string | null | undefined): string {
    return value ? labels[value] ?? value : "—";
}
export function itError(value: string | null | undefined): string {
    if (!value) return "Die aksie kon nie voltooi word nie. Probeer asseblief weer.";
    if (labels[value]) return labels[value];
    // Application-generated Afrikaans errors may pass through; raw API diagnostics stay out of the UI.
    if (/^(Die |Jy |Jou |Geen |Kies |Vul |Slegs |Daar |Voornaam|Ongeldige|Tik |Versoek)/.test(value)) return value;
    return "Die aksie kon nie voltooi word nie. Verfris die bladsy en probeer weer. Kontak IT-ondersteuning indien dit voortduur.";
}
